### PR TITLE
fix documentation and formating

### PR DESCRIPTION
**Pull request by schurzi**

### CODE REVIEW

**Comment by aleex42** [comment]
Sorry for waiting so long to merge your stuff. Now we've got many conflicts :(

Could you resolve these conflicts?

**Comment by aleex42** [comment]
But I cannot merge because of conflicts :(

**Comment by schurzi** [comment]
I'll try to resolve the conflicts, but maybe it would be faster to redo my changes to the new code.  Please only merge, once I have responded with my explicit OK.

**Comment by schurzi** [comment]
I think, this is OK now. Please review and comment/merge

**Comment by aleex42** [comment]
Looks good. Thanks! 👍

**Pull request merged**
